### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#3]
I tried to install as described in the docs with the following steps:
```bash
git clone https://github.com/pytroll/pygac-fdr.git
cd pygac-fdr/
conda create --prefix ./venv python=3.7 anaconda
conda activate ./venv
pip install .
```
Unfortunately, I ended up with the following error:
```bash
Processing /DSNNAS/Repro_Temp/users/mattes/pygac_test/fdr/pygac-fdr
    ERROR: Command errored out with exit status 1:
     command: /DSNNAS/Repro_Temp/users/mattes/pygac_test/fdr/pygac-fdr/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gvzypuzb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gvzypuzb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-gvzypuzb/pip-egg-info
         cwd: /tmp/pip-req-build-gvzypuzb/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gvzypuzb/setup.py", line 25, in <module>
        version = importlib.import_module('pygac_fdr.version').__version__
      File "/DSNNAS/Repro_Temp/users/mattes/pygac_test/fdr/pygac-fdr/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-gvzypuzb/pygac_fdr/__init__.py", line 19, in <module>
        from satpy.utils import get_logger
    ModuleNotFoundError: No module named 'satpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Seems like it does not find `satpy` using the current `setup.py`. 
I manually installed `satpy` and re-tried and it worked.
```
pip install satpy
pip install .
```

**Comment by mraspaud** [comment]
that looks like an error: @sfinkens why do you import satpy's get_logger and not go directly against the logging module ? The trace level shouldn't be needed in most cases.
Something like:
```python
log = logging.getLogger(name)
```
?

**Comment by sfinkens** [comment]
Sorry, I hadn't really finished the logging stuff and this was a testing leftover. See #5 for a better logging approach. This also fixes the installation error.
